### ISSUE TITLE
failure to import cuosqp

### ISSUE THREAD

**Issue by ArGenya** [osqp/cuosqp#10]
When I was trying to run `import cuosqp` in Python3, I got the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cuosqp-0.1.0-py3.8-linux-x86_64.egg/cuosqp/__init__.py", line 1, in <module>
    from cuosqp.interface import OSQP
  File "/usr/local/lib/python3.8/dist-packages/cuosqp-0.1.0-py3.8-linux-x86_64.egg/cuosqp/interface.py", line 5, in <module>
    import cuosqp._osqp as _osqp  # Internal low level module
ImportError: /usr/local/lib/python3.8/dist-packages/cuosqp-0.1.0-py3.8-linux-x86_64.egg/cuosqp/_osqp.cpython-38-x86_64-linux-gnu.so: undefined symbol: __cxa_pure_virtual
```

The corresponding environment variables are:
        CUDA_PATH: `/usr/local/cuda`
        CUDACXX: `/usr/local/cuda/bin/nvcc`

I suspect that the object file `_osqp.cpython-38-x86_64-linux-gnu.so` wasn't correctly compiled. It might have functions that weren't correctly linked. Any of your help will be greatly appreciated!

**Comment by gbanjac** [comment]
The same issue has already been reported in https://github.com/osqp/cuosqp/issues/8 so I am closing this one.
