### ISSUE TITLE
ImportError: DLL load failed while importing _osqp

### ISSUE THREAD

**Issue by lalajiayou** [osqp/cuosqp#15]
I have successfully installed cuosqp. **While when I run the basic_tests.py, the program reports an error as shown below.** 
Looking forward to getting a reply.

![image](https://github.com/osqp/cuosqp/assets/30371734/64ee9643-c745-4080-943f-34df6679d4b8)

Traceback (most recent call last):
  File "D:\anaconda202202\Lib\site-packages\cuosqp-0.1.0-py3.9-win-amd64.egg\cuosqp\utils.py", line 5, in <module>
    import cuosqp._osqp as _osqp
  File "D:\anaconda202202\lib\site-packages\cuosqp-0.1.0-py3.9-win-amd64.egg\cuosqp\__init__.py", line 1, in <module>
    from cuosqp.interface import OSQP
  File "D:\anaconda202202\lib\site-packages\cuosqp-0.1.0-py3.9-win-amd64.egg\cuosqp\interface.py", line 5, in <module>
  import cuosqp._osqp as _osqp  # Internal low level module
ImportError: DLL load failed while importing _osqp: the given module is not found

**Comment by serre20** [comment]
How do you solve this problem?

**Comment by lalajiayou** [comment]
您好，已经收到您发来的邮件，会尽快给您回复。
