### ISSUE TITLE
undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by yz-mao** [osqp/cuosqp#6]
Hello, 
I set the CUDA_PATH in `setup.py` to be:

>  `CUDA_PATH = "/usr/local/cuda/"` 

and these messages are shown during the `python setup.py install` step:

> -- The CUDA compiler identification is NVIDIA 11.1.74
   Found CUDA: /usr/local/cuda (found version "11.1")

After the installation, I check the CUDA version by `nvcc -V`, and it shows:

> `Cuda compilation tools, release 11.1, V11.1.74`

However, while I `import cuosqp` in python, it raises error like this:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/XXX/anaconda3/lib/python3.6/site-packages/cuosqp-0.1.0-py3.6-linux-x86_64.egg/cuosqp/__init__.py", line 1, in <module>
    from cuosqp.interface import OSQP
  File "/home/XXX/anaconda3/lib/python3.6/site-packages/cuosqp-0.1.0-py3.6-linux-x86_64.egg/cuosqp/interface.py", line 5, in <module>
    import cuosqp._osqp as _osqp  # Internal low level module
ImportError: /home/XXX/anaconda3/lib/python3.6/site-packages/cuosqp-0.1.0-py3.6-linux-x86_64.egg/cuosqp/_osqp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

I am wondering why it happens and how to fix it? Thank you in advance.

**Comment by yz-mao** [comment]
I changed the soft link from `cuda-11.1` to `cuda-11.0`, and then created a new environment to install this again. This time it works well. Thank you for the wonderful work!
